TRAINING_DATA = [
    {"text": "Schedule meeting with client for project review", "category": "Work"},
    {"text": "Prepare sprint planning presentation for the team", "category": "Work"},
    {"text": "Deploy new feature to production server", "category": "Work"},
    {"text": "Write quarterly results report for stakeholders", "category": "Work"},
    {"text": "Complete task before the deadline this week", "category": "Work"},
    {"text": "Review pull request from team member", "category": "Work"},
    {"text": "Update project timeline and milestones", "category": "Work"},
    {"text": "Send client proposal for new project", "category": "Work"},
    {"text": "Organize team standup meeting", "category": "Work"},
    {"text": "Create board meeting presentation slides", "category": "Work"},
    {"text": "Assign tasks to team members for sprint", "category": "Work"},
    {"text": "Review client feedback on project deliverables", "category": "Work"},
    {"text": "Plan weekend trip with family", "category": "Personal"},
    {"text": "Buy birthday gift for close friend", "category": "Personal"},
    {"text": "Organize dinner party at home", "category": "Personal"},
    {"text": "Book vacation flights for summer travel", "category": "Personal"},
    {"text": "Take pet to veterinary clinic", "category": "Personal"},
    {"text": "Call friend to catch up on life", "category": "Personal"},
    {"text": "Plan birthday surprise party", "category": "Personal"},
    {"text": "Clean and organize home office space", "category": "Personal"},
    {"text": "Weekend hobby shopping list", "category": "Personal"},
    {"text": "Family reunion planning and coordination", "category": "Personal"},
    {"text": "Arrange vacation photos from last trip", "category": "Personal"},
    {"text": "Help friend move to new home", "category": "Personal"},
    {"text": "Morning run followed by gym session", "category": "Health"},
    {"text": "Book appointment with doctor for checkup", "category": "Health"},
    {"text": "Prepare healthy meal plan for the week", "category": "Health"},
    {"text": "Practice yoga for flexibility and calm", "category": "Health"},
    {"text": "Track daily water intake goals", "category": "Health"},
    {"text": "Get enough sleep tonight for recovery", "category": "Health"},
    {"text": "Take daily medicine and vitamins", "category": "Health"},
    {"text": "Schedule annual health checkup", "category": "Health"},
    {"text": "Exercise routine for strength training", "category": "Health"},
    {"text": "Diet plan review for weight loss", "category": "Health"},
    {"text": "Join gym membership for regular exercise", "category": "Health"},
    {"text": "Research healthy recipes for diet plan", "category": "Health"},
    {"text": "Review monthly budget and expenses", "category": "Finance"},
    {"text": "Research stock investment opportunities", "category": "Finance"},
    {"text": "Pay electricity and internet bills", "category": "Finance"},
    {"text": "Check bank account balance online", "category": "Finance"},
    {"text": "File tax returns before deadline", "category": "Finance"},
    {"text": "Review stock portfolio performance", "category": "Finance"},
    {"text": "Plan savings for emergency fund", "category": "Finance"},
    {"text": "Track salary and income sources", "category": "Finance"},
    {"text": "Make credit card payment on time", "category": "Finance"},
    {"text": "Compare insurance plans and rates", "category": "Finance"},
    {"text": "Set up automatic bill payment system", "category": "Finance"},
    {"text": "Calculate tax deductions for the year", "category": "Finance"},
    {"text": "Complete online course on machine learning", "category": "Learning"},
    {"text": "Read research paper on neural networks", "category": "Learning"},
    {"text": "Practice new skill with online tutorial", "category": "Learning"},
    {"text": "Attend data science workshop", "category": "Learning"},
    {"text": "Study for upcoming certification exam", "category": "Learning"},
    {"text": "Learn new framework from documentation", "category": "Learning"},
    {"text": "Watch lecture on algorithms and data structures", "category": "Learning"},
    {"text": "Write notes from book chapter", "category": "Learning"},
    {"text": "Join study group for class preparation", "category": "Learning"},
    {"text": "Research latest trends in AI technology", "category": "Learning"},
    {"text": "Enroll in advanced Python course", "category": "Learning"},
    {"text": "Practice coding problems daily for skill improvement", "category": "Learning"},
    {"text": "Design new logo for brand identity", "category": "Creative"},
    {"text": "Write blog post about technology trends", "category": "Creative"},
    {"text": "Edit photos from recent photoshoot", "category": "Creative"},
    {"text": "Compose music track for video project", "category": "Creative"},
    {"text": "Create digital art illustration", "category": "Creative"},
    {"text": "Paint landscape from reference photo", "category": "Creative"},
    {"text": "Write creative short story", "category": "Creative"},
    {"text": "Record and edit video content", "category": "Creative"},
    {"text": "Sketch character design concepts", "category": "Creative"},
    {"text": "Plan creative photography session", "category": "Creative"},
    {"text": "Design website layout and wireframe", "category": "Creative"},
    {"text": "Write song lyrics and compose melody", "category": "Creative"},
    {"text": "Team meeting about budget planning", "category": "Work"},
    {"text": "Learn to invest and save money wisely", "category": "Finance"},
    {"text": "Write music and create digital art", "category": "Creative"},
    {"text": "Exercise and study for better health knowledge", "category": "Health"},
    {"text": "Travel home for family birthday celebration", "category": "Personal"},
    {"text": "Research paper on health and diet science", "category": "Learning"},
    {"text": "Design presentation for client project meeting", "category": "Work"},
    {"text": "Book course on creative writing skill development", "category": "Learning"},
]